### ISSUE TITLE
Uniform distribution instead of Gaussian distribution

### ISSUE THREAD

**Issue by jan1854** [ku2482/slac.pytorch#5]
Hi,

I think there might be a slight error in the LatentModel. For sampling the latent states, the function `torch.rand_like()` is used, which samples from a uniform distribution. According to the paper (see appendix B) and the original implementation the latent states should be sampled from a Gaussian distribution, however. This can be fixed by replacing `torch.rand_like()` with `torch.randn_like()` In lines 193, 196, 204, 207, 226, 229, 239, 242 of network/latent.py.

Best regards,
Jan

**Comment by toshikwa** [comment]
You're right, they are typos...
Could you send a pull request?

Thank you for pointing out.

**Comment by jan1854** [comment]
There you go: #6
