### ISSUE TITLE
doubt: What exactly is the use of masks while learning the model? Can't you just use "done" variable instead of it?

### ISSUE THREAD

**Issue by aravindvenu7** [ku2482/slac.pytorch#7]
https://github.com/ku2482/slac.pytorch/blob/d68f42582180d38735496a24cddbf0523726973d/slac/algo.py#L113

**Comment by toshikwa** [comment]
If the agent fails, MDP ends. However, if the agent doesn't fail, MDP continues.
Therefore, if we force to terminate the episode when the agent doesn't fail, we introduce the bias.
So we mask termination signals at the end of episodes (because MDP would continue.)

Does it make sense?
